bbc/bigscreen-player

package-lock.json
script-test/playbackstrategies/msestrategytest.js
script/debugger/debugview.js
script/playbackstrategy/msestrategy.js
script/plugins.js

facilitating reporting of dash playback bitrate and the buffer length through plugins.
Also address some styling issues to the onscreen debug tool.

Expose player bitrate

---

script/debugger/debugview.js
script/playbackstrategy/msestrategy.js

This PR logs playback and buffer stalled events from DASH.js and improves the debug tool output performance.

Improve Playback/Buffer Stalled Logging & Debug Tool Performance

---

gruntfile.js
spec/support/boot.js

Added back the custom environment setup for the Jasmine spec.

Fix jasmine env

---

script-test/playercomponenttest.js
script/bigscreenplayer.js
script/dynamicwindowutils.js
script/models/livesupportenum.js
script/playercomponent.js

Webcast Failover for Seekable HLS Devices

---

package-lock.json
package.json

Update the version to 2.2.3 that contains #67

Prepare Release 2.2.3

---

package-lock.json
package.json

Update package version to 2.3.0

---

script-test/bigscreenplayertest.js
script/bigscreenplayer.js

Function returns:
* `true` if playing LIVE media and current time is within 10 seconds of the seekable range end
* `false` if not initialised, playing ON DEMAND media, or not playing in last 10 seconds

New API function isPlayingAtLiveEgde()

---

package-lock.json
package.json

Update package.json to 2.11.0 for release.
Contains:
- #83 Consolidate Failover Logic

update version to v2.11.0

---

package-lock.json
package.json

📺 What
Update package and lock with new version

Prepare release 3.2.0

---

package-lock.json
package.json

📺 What
Update package and package-lock to 3.3.0
> Tickets: IPLAYERTVV1-9617, IPLAYERTVV1-9708

Updated version to 3.3.0

---

package-lock.json
package.json

📺 What
Prepare release version by updating package and package-lock files.

Prepare release 3.4.0

---

package-lock.json
package.json
script-test/playbackstrategies/msestrategytest.js
script-test/utils/timeutilstest.js
script/playbackstrategy/msestrategy.js
script/utils/timeutils.js

📺 What
Consolidate seek behaviour between static and dynamic DASH streams in `msestrategy`.
> See issue #4 
🛠 How
Correctly calculate the time spent 'seeking' within a UI based upon the pause transition and apply the correct relative time to the dash.js `mediaplayer.seek` function.

Use dash.js mediaPlayer seek for static and dynamic DASH streams

---

development/index.js

📺 What
When creating #118 there were a few parameters missed from the `init` method of bigscreen player. This PR just adds them in.
🛠 How
Add callbacks, toggle the debug tool regardless so you can see any debug output when the dev server reloads.
Also add a reference to the bigscreenplayer instance on the window so it can be interacted with in the console easily.

Update development script with complete init api

---

package-lock.json
package.json
script-test/playbackstrategies/msestrategytest.js
script/playbackstrategy/msestrategy.js
script/version.js

📺 What
This emits the full playbackBitrate from `msestrategy`
🛠 How
The current representation bitrates for video and audio are combined and emitted as `playbackBitrate` through Plugins.interface.onPlayerInfoUpdated.

Correct bitrate plugin metric

---

development/index.js
package-lock.json
package.json
webpack.config.js

📺 What
Update dependencies for the main project. 
A small change was required for the dev env as html-webpack-template is no longer required.
> Tickets: N/A
🛠 How
Update the `package.json`, `package-lock.json` and supporting files.

Dependency Audit May

---

package-lock.json
package.json
script/mockbigscreenplayer.js
script/version.js

📺 What
Follow up to https://github.com/bbc/bigscreen-player/pull/137.
Make `registerForSubtitleChanges` work as expected with the mock.
> Tickets: IPLAYERTVV1-11166
🛠 How
Update `MockBigScreenPlayer`

update MockBigScreenPlayer to support subtitle changes

---

package-lock.json
package.json
script/version.js

Bump version to 3.14.3

---

README.md

📺 What
Update release documentation.
🛠 How
Change the README.

Improve release documentation

---

README.md

📺 What
Improve docs on playback strategies.
> Tickets: N/A
🛠 How
Update README.

Improve playback strategy info in README.

---

CONTRIBUTING.md
README.md

📺 What
Add contribution guidelines
> Tickets: N/A
🛠 How
CONTRIBUTING.md

Proposal for contribution guidelines

---

.github/PULL_REQUEST_TEMPLATE.md

📺 What
Include test engineer sign off in PR process.
> Tickets: IPLAYERTVV1-10897
🛠 How
Add test engineer sign off box to PR template.

Add test engineer sign off box to PR template.

---

package-lock.json
package.json
script/version.js

📺 What
Prepare for release 3.15.0
🛠 How
Bump `package.json`, `package-lock.json` and `version.js`

Prepare version 3.15.0

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

📺 What
Link to testing guidelines in wiki.
> Tickets: IPLAYERTVV1-10897
🛠 How
Update PR template and CONTRIBUTING.m,
N/A - docs only

Add links to test guidelines wiki.

---

package-lock.json
package.json
script/version.js

📺 What
Update to 3.15.1
> Tickets: IPLAYERTVV1-10179
🛠 How
Bump the Patch Version

Update to 3.15.1

---

script-test/playbackstrategies/modifiers/html5tests.js

📺 What
Exit buffering sentinel was being fired after the end of a test causing flakey tests. Also removed a call to metadataCallback that also fails intermittently. 
> Tickets: N/A
🛠 How
html5tests update.

Fix the flakey html5 tests

---

package-lock.json
package.json
script/version.js

📺 What
Increase minor version to 3.17.0
[Add the jira ticket and/or the ADR to this PR]
> Tickets: IPLAYERTVV1-10639
🛠 How
add verbose log level and initial reporting of dashjs log events
[MANDATORY for contributions being tested and released by the contributing team]
[How will this change be tested?]
✅ Acceptance criteria [Optional]
[MANDATORY for cross-team reviews]

Prepare release of 3.17.0

---

package.json

📺 What
This removes the pre-commit checks that lint and test before committing. 
Given we have pre-push checks doing this same thing, this is being removed.
🛠 How
Remove pre-commit script.

Remove pre-commit check

---

script-test/bigscreenplayertest.js
script/mockbigscreenplayer.js

📺 What
Ensure mockbigscreenplayer is kept up to date. 
> Tickets: IPLAYERTVV1-XXXX
🛠 How
When using mock or mockJasmine, loop through all functions on bigscreenplayer api to ensure they are mocked (or not, if on an exclude list).

Mock update

---

development/index.js
script-test/subtitles/captionscontainer.js
script-test/subtitles/renderer.js
script-test/subtitles/transformer.js
script/plugins.js
script/subtitles/captionscontainer.js
script/subtitles/renderer.js
script/subtitles/transformer.js

📺 What
Fire plugin events when subtitles are determined to have errored.
> Tickets: IPLAYERTVV1-11772
🛠 How
Add new interface methods:
- `onSubtitlesLoadError`
- `onSubtitlesTransformError`
- `onSubtitlesRenderError`

Add plugin events for subtitle errors

---

package.json

📺 What
Temporarily add `postinstall` step. Add `build` folder to `dist`.
> Tickets: N/A

Build dist updates

---

README.md

📺 What
Update readme
> Tickets: IPLAYERTVV1-11997
🛠 How
Update readme

Added readme changes for subtitle work

---

package-lock.json
package.json
script-test/subtitles/imscsubtitles.js
script-test/subtitles/legacysubtitles.js
script/plugins.js
script/subtitles/imscsubtitles.js
script/subtitles/legacysubtitles.js
script/utils/loadurl.js

📺 What
Adds two new plugin events for more granularity of subtitle errors (timeout and xml errors). 
> Tickets: IPLAYERTVV1-11795
🛠 How
Add to the plugin interface and fire these when appropriate from both imscsubtitles and legacysubtitles.

Extend subtitle plugin events

---

script-test/subtitles/imscsubtitles.js
script-test/subtitles/legacysubtitles.js
script-test/subtitles/renderer.js
script/subtitles/imscsubtitles.js
script/subtitles/legacysubtitles.js
script/subtitles/renderer.js

📺 What
* Legacy subs - Only load sub urls when required
* IMSC subs - Don't keep loading subtitles for VOD on start/stop
> Tickets: IPLAYERTVV1-11796
🛠 How
* Put the current initial loading of subtitles behind an autoStart check. (Similar to IMSC implementation)
* if autoStart is false and subtitles are started mid stream. Load subs before starting.

Legacy subs - Only load subtitle urls when required

---

package-lock.json

📺 What
Update dependencies raised by dependabot

NPM Audit: Update Dependencies

---

README.md

📺 What
Adds the BSP logo to the documentation
🛠 How
Added a HTML `<img>` tag to the README. I used this so that I could set the width and have the browser scale it. Not the best performance-wise, but it looks very nice and crisp 😄 
♿  Accessibility [optional]
- Correct alt tag used on `<img>` tag

Adding BSP logo

---

CODEOWNERS

make @bbc/honey-badger-core code owners

---

src/plugins.js
src/subtitles/subtitles.js

📺 What
* Catch any dynamic load errors
> Tickets: IPLAYERTVV1-12793
🛠 How
* Added a catch to the dynamic subtitle loads for imsc/legacy.
* Added a new dynamic subtitles error to the plugin interface.

Dynamic subtitles catch and plugin

---

src/playbackstrategy/modifiers/html5.js

📺 What
Allows configurable seekable range caching
> Tickets: IPLAYERTVV1-12900
🛠 How
Prevents the seekable start/end functions from being called more than once every 250ms.

Configurable caching of seekable range

---

.github/PULL_REQUEST_TEMPLATE.md

📺 What
Update the PR Template to remove requirement for Ticket Link
> Tickets: N/A
🛠 How
Democracy

Update the PR Template to remove requirement for Ticket Link

---

.eslintrc.yaml
src/bigscreenplayer.js

📺 What
Remove the compat for the old API of `bspData.media.captionsUrl` now we are Version 6
🛠 How
Remove the compat for the old API of `bspData.media.captionsUrl`

Remove old API Compat

---

src/bigscreenplayer.test.js
src/debugger/chronicle.test.js
src/debugger/debugtool.test.js
src/playbackstrategy/modifiers/cehtml.test.js
src/playbackstrategy/modifiers/html5.test.js
src/playbackstrategy/modifiers/live/playable.test.js
src/playbackstrategy/modifiers/live/restartable.test.js
src/playbackstrategy/modifiers/live/seekable.test.js
src/playbackstrategy/modifiers/samsungmaple.test.js
src/playbackstrategy/modifiers/samsungstreaming.test.js
src/playbackstrategy/modifiers/samsungstreaming2015.test.js
src/playbackstrategy/msestrategy.test.js
src/playercomponent.test.js
src/resizer.test.js
src/subtitles/legacysubtitles.test.js
src/subtitles/renderer.test.js
src/subtitles/transformer.test.js
src/utils/callcallbacks.test.js
src/utils/deferexception.test.js
src/utils/timeutils.test.js
src/version.test.js

📺 What
Fixes some of the eslint errors on the test files. 
🛠 How
Mixture of auto-fix and manual fixes.

Fix linting errors on test files

---

CONTRIBUTING.md

📺 What
Update CONTRIBUTORS.md doc to fix a broken link and update some information.
🛠 How
Edit markdown file.

Update CONTRIBUTORS.md doc

---

docs/tutorials/Configuration.md
docs/tutorials/Plugins.md
src/playbackstrategy/msestrategy.js
src/playbackstrategy/msestrategy.test.js
src/plugins.js

📺 What
This plugin exposes Dash's `FRAGMENT_CONTENT_LENGTH_MISMATCH` to consumers of BSP.
🛠 How
Hook Dash's Event into BSP's Plugin System
👀 See
https://github.com/bbc/bigscreen-player/tree/badgers-107-dash-v4

`onFragmentContentLengthMismatch` plugin

---

package-lock.json
package.json

📺 What
Update dash.js to the latest bbc/dash.js release.
🛠 How
Update dash.js dependency to the smp-v4.7.3-0 tag.

Update to bbc/dash.js#smp-v4.7.3-0

---

index.html
src/playbackstrategy/msestrategy.js
src/plugins.js

📺 What
Hook into the dash.js `quotaExceeded` event to report to a quota exceeded plugin.
🛠 How
- Add a listener for `quotaExceeded`
- Add the `onQuotaExceeded` plugin function

Add QuotaExceededPlugin

---

src/playbackstrategy/msestrategy.js

📺 What
Fix for leftover from exploratory coding
🛠 How
Instead of splatting, don't

Don't splat `quotaExceededTime`

---

docs/tutorials/Debugging.md
src/bigscreenplayer.js

📺 What
Title.
🛠 How
Replace JSDoc imports with ES imports

BADGERS-307 patch: Fix docs

---

src/debugger/chronicle.ts
src/debugger/debugtool.test.ts
src/debugger/debugtool.ts
src/playbackstrategy/basicstrategy.js
src/playbackstrategy/legacyplayeradapter.js
src/playbackstrategy/msestrategy.js

📺 What
Tweak data out of Chronicle
🛠 How
Add apicall trace
Add playback rate metric
Log seamless failover errors
Stop sending stalled events
Take current element time from the media element

BADGERS-380 feat(chronicle): tweak the data

---

.eslintrc.yaml
src/bigscreenplayer.js
src/debugger/debugviewcontroller.ts

📺 What
Title.
🛠 How
Add missing trace types to the debug view
Stop updating time from bigscreenplayer in favour of writing time per strategy

BADGERS Fix debugview

---

package-lock.json
package.json

📺 What
Title. This release replaces `emitSyntheticStallEvents` with a `syntheticStallEvents block. See: https://github.com/bbc/dash.js/pull/91
🛠 How
https://github.com/bbc/dash.js/pull/91

Take `bbc/dash.js#smp-4.7.3-1`

---

src/playbackstrategy/msestrategy.js

📺 What
Remove Event Listener for Quota Exceeded in Teardown
🛠 How
Remove Event Listener for Quota Exceeded in Teardown

Remove Event Listener for Quota Exceeded in Teardown

---

src/bigscreenplayer.js
src/debugger/chronicle.ts

📺 What
Change Duration from Dynamic to Static Metric
🛠 How
Change Duration from Dynamic to Static Metric

Change Duration from Dynamic to Static Metric

---

src/plugins.js
src/plugins.test.js

📺 What
Defer plugin exceptions.
https://jira.dev.bbc.co.uk/browse/BADGERS-309
🛠 How
Use callCallbacks in the plugins.

Defer plugin exceptions

---

package-lock.json
package.json
src/playbackstrategy/msestrategy.js
src/plugins.js
src/plugins.test.js

📺 What
Fixes an issue where a user pause in a session preceding a seek in Sliding Window content could erroneously offset the seek by the time paused.
🛠 How
Distinguish between a `USER` and `APP` pause in calculating offset time

Fix Pause before Seek Scenario for Sliding Window

---

src/subtitles/legacysubtitles.js

📺 What
Add some inline layout styles for legacy subtitles

Add inline styles for legacy subtitles container

---

src/playbackstrategy/msestrategy.js

📺 What
Count and publish the number of manifest loads
🛠 How
When a manifest has finished loading increase the count. Once it has fully loaded publish and reset.

Added manifest load count

---

package-lock.json
package.json

📺 What
Bump Dash to v4.7.3-5
🛠 How
Bump Dash to v4.7.3-5

Bump Dash to v4.7.3-5

---

package-lock.json
package.json
src/playbackstrategy/msestrategy.js

📺 What
Updates Dash.js with new version (smp-v4.7.3-12) to fix logic in `videoFramesNotAdvancing` function.
🛠 How
Brings in fix to `isEnded` within `videoFramesNotAdvancing` function in Dash.js.

Video frames not advancing updates
