bbc/bigscreen-player

- script-test/playbackstrategies/msestrategytest.js
- script/playbackstrategy/msestrategy.js
This adds in some smaller defaults to the buffer size used by DashJS. These are noticeably smaller than those defined by the library. See documentation [here](http://cdn.dashjs.org/latest/jsdoc/module-MediaPlayer.html#setBufferAheadToKeep__anchor).
> Set Smaller DashJS Buffer Defaults

- script-test/playbackstrategies/msestrategytest.js
- script/playbackstrategy/msestrategy.js
Reverts bbc/bigscreen-player#7
Manual testing found that this change results in playback entering buffering and never recovering. We're investigating why this is the case.
> Revert "Set Smaller DashJS Buffer Defaults"

- script-test/playbackstrategies/msestrategytest.js
Fixing some MSE unit tests that didn't fail as expected that were relating to audio and video tags.
> fix test to catch non returning video element and improve consistency

- script/captions.js
The current implementation is wrong, DebugTool.error expects a particular object format... info() is a better fit for logs like this.
> change DebugTool.error usages in captions.js to info

- script-test/playbackstrategies/msestrategytest.js
- script/bigscreenplayer.js
- script/debugger/debugview.js
- script/playbackstrategy/msestrategy.js
I've added in some extra hooks to the dash.js metric events with some interesting information for debugging playback.
ABR change debug messages have the bitrate in the message along with the current bitrate being shown on the key value pane (as the TAL strategy does it).
Buffer level has also been added to the key value pane.
> add in debug tool enhancements. ABR levels, bitrates and buffer length.

- package-lock.json
- script-test/playbackstrategies/legacyplaybackadaptortest.js
- script-test/playbackstrategies/msestrategytest.js
- script-test/playercomponenttest.js
- script/bigscreenplayer.js
- script/playbackstrategy/legacyplayeradapter.js
- script/playbackstrategy/msestrategy.js
- script/playercomponent.js
Failover for LIVE playback - DASH only.
- Native Strategy - uses the `load` functions `startTime` argument as the time to failover to. This is passed in by `playerComponent` using `getCurrentTime`, which is the native strategy's internally stored current time.
- MSE Strategy - ignores the `load` functions `playbackTime` argument and instead uses the MSE strategy's internally stored `failoverTime`.
Refactoring unit tests.
> Live cdn failover

- script/playbackstrategy/msestrategy.js
Sliding window CDN failover using dash.js was previously using the time correction based on the initial stream start time to determine the time to restart. 
This causes the time that CDN failover occurs to drift by the amount of time you have been watching a live stream.
It was also possible to failover to just behind the live point when watching from the start of a window, so this has been clamped to 0 for this case. This was due to #r= using negative numbers, IN_STREAM_BUFFERING being 20 seconds and the `failoverTime` being < 20.
> Live CDN failover time fix

- script-test/playbackstrategies/msestrategytest.js
- script-test/playercomponenttest.js
- script/playbackstrategy/msestrategy.js
- script/playercomponent.js
- script/plugindata.js
onErrorHandled plugin now passes both the CDN we are failing over _**from**_ and the CDN we are failing over _**to**_.
This will be useful to clients whose implementation wishes to know both pieces of information.
Failover may happen in either `playercomponent` or `msestrategy`, depending on the type of failover (standard buffering timeout or silent failover using dash manifest base urls).
> Report new cdn to plugin when failing over

- script-test/playbackstrategies/msestrategytest.js
- script/playbackstrategy/msestrategy.js
Changed when we modify the manifest. Now done on dashjs `manifestLoaded` event (which returns the manifest object), rather than manually retrieving it and attaching the object on startup. 
**Note:** Since `refreshManifest` was asynchronous and not effectively updating the `DVRInfo.range.end` in time for seeking, it was placed in the same code path as `WindowTypes.STATIC`.
> DASH MSE Webcast Enhancement

- package-lock.json
- package.json
- script-test/bigscreenplayertest.js
- script-test/playbackstrategies/modifiers/live/playabletest.js
- script-test/playbackstrategies/modifiers/live/restartabletest.js
- script-test/playbackstrategies/modifiers/live/seekabletest.js
- script-test/playbackstrategies/nativestrategytest.js
- script-test/playercomponenttest.js
- script/dynamicwindowutils.js
- script/playbackstrategy/modifiers/html5.js
- script/playbackstrategy/modifiers/live/playable.js
- script/playbackstrategy/modifiers/live/restartable.js
- script/playbackstrategy/modifiers/live/seekable.js
- script/playbackstrategy/nativestrategy.js
- script/playercomponent.js
- spec/support/boot.js
We can simulate seeking by creating a fake version of the current time (and seekable range), and then restarting (complete teardown) the media player to begin playback from the user's input seeking time. This will enable `restartable` devices with unreliable `mediaElement.currentTime` to now have seeking capabilities.
> Teardown seeking for restartable devices

- package.json
- script-test/manifest/manifestmodifiertest.js
- script/manifest/manifestmodifier.js
- script/playbackstrategy/msestrategy.js
Added configurable option for reverting all `avc3` video container formats in the dash manifest to `avc1`. This can be set by the option `window.bigscreenPlayer.oldDashCodecRequired`.
> Unsupported dash codec

- package-lock.json
- package.json
- script-test/mediaresiliencetest.js
- script-test/playbackstrategies/strategypickertest.js
- script-test/playercomponenttest.js
- script/mediaresilience.js
- script/models/playbackstrategy.js
- script/playbackstrategy/hybridstrategy.js
- script/playbackstrategy/modifiers/live/restartable.js
- script/playbackstrategy/strategypicker.js
Using the `restartable` fake time functionality, we can now allow live CDN failover on `nativestrategy`, `restartable` devices. As part of this work, a configurable window flag (`window.bigscreenPlayer.disableLiveFailover`) can be set to disable live failover for any specific conditions.
> Failover on Native-Restartable devices

- package-lock.json
- package.json
- script-test/playbackstrategies/modifiers/cehtmltests.js
- script/playbackstrategy/legacyplayeradapter.js
- script/playbackstrategy/modifiers/cehtml.js
- script/playbackstrategy/modifiers/live/none.js
- script/playbackstrategy/modifiers/live/restartable.js
- script/playbackstrategy/nativestrategy.js
Add the cehtml player as an alternative to the html5 player. Setting `window.bigscreenPlayer.mediaPlayer` to `cehtml` will enable this, leaving it unset or setting it to `html5` will use the existing player
> Add cehtml player to native strategy

- package-lock.json
📺 What
Prepare release 3.0.0.
🛠 How
Update `package-lock`. Previous commit to master updated the `package.json` but I forgot to do the `package-lock`
> Prepare release 3.0.0 - update package lock

- script-test/playbackstrategies/msestrategytest.js
- script/playbackstrategy/msestrategy.js
📺 What
This adds the fragment download time of a dash fragment **(MSE only)** to the `onPlayerInfoUpdated` plugin callback.
> Tickets: IPLAYERTVV1-8976
🛠 How
This uses the `HttpList` object passed through when a dash metric is added to the player, and propagates the time it took the request in it's entirety to the plugins.
> Report fragment request time to the plugins

- script-test/playbackstrategies/growingwindowrefreshertest.js
- script-test/playbackstrategies/msestrategytest.js
- script/playbackstrategy/growingwindowrefresher.js
- script/playbackstrategy/msestrategy.js
📺 What
Prevent seeking beyond the end of a growing window stream, which will result in multiple 404's and eventually a fatal error.
> Tickets: IPLAYERTVV1-9617
🛠 How
Refreshes the manifest when seeking forwards in a GROWING WINDOW asset. If the asset has ended, and the manifest contains a `mediaPresentationDuration`, the seek time will be clamped to this.
> Growing window manifest refresh

- package-lock.json
- package.json
📺 What
Update dash.js to [v2.9.3-3](https://github.com/bbc/dash.js/releases/tag/smp-v2.9.3-3)
🛠 How
[Changelog between 2.9.3-0 and 2.9.3-3](https://github.com/bbc/dash.js/compare/smp-v2.9.3-0...smp-v2.9.3-3)
> Update dash.js to 2.9.3-3

- script-test/bigscreenplayertest.js
- script-test/playbackstrategies/legacyplayeradaptortest.js
- script-test/playbackstrategies/msestrategytest.js
- script-test/playercomponenttest.js
- script/mediasources.js
- script/mockbigscreenplayer.js
- script/playbackstrategy/legacyplayeradapter.js
- script/playbackstrategy/msestrategy.js
- script/playercomponent.js
📺 What
Clears up various points in the code where playback properties are still sent on plugin events, most notably `event_history`. These were missed as part of #92
> Tickets: IPLAYERTVV1-9719
🛠 How
Deleting the code! Plugin events should no longer be emitting any `properties`.
> Clear up playback properties on plugin events - missed as part of #92

- package-lock.json
- package.json
- script-test/bigscreenplayertest.js
- script/bigscreenplayer.js
- script/debugger/debugpresenter.js
- script/debugger/debugtool.js
- script/debugger/debugview.js
📺 What
Slightly improve the media debug tool.
🛠 How
1. Attach the debug tool to the same parent DOM node as the media element.
2. Tear it down correctly.
3. Also show the current log contents immediately on enabling instead of waiting for an event.
> Improve The Debug Tool

- package-lock.json
- package.json
- script-test/bigscreenplayertest.js
- script/bigscreenplayer.js
- script/mockbigscreenplayer.js
📺 What
Add some context when buffering, to inform consumers if the WAITING event was triggered following a seek.
> Tickets: IPLAYERTVV1-10049
🛠 How
* `isSeeking` parameter is added to the WAITING state object.
* Set a flag in bigscreenplayer.js when the `setCurrentTime` method is called.
* Use this flag as the `isSeeking` value
* Clear flag after the WAITING event is emitted.
> Add seeking context to WAITING event. Clear after firing the event

- .eslintignore
- README.md
- buildVersion.js
- package-lock.json
- package.json
- script-test/bigscreenplayertest.js
- script-test/version.js
- script/bigscreenplayer.js
- script/version.js
📺 What
This exposes the current framework version on the public api as `BigscreenPlayer.version`
🛠 How
This updates the framework version available at runtime based upon the package lock.
`npm run pre-release:patch|minor|major` does `npm version patch|minor|major` then updates the version JS module.
> Add Framework Version

- script/playercomponent.js
📺 What
Remove unused dependency from PlayerComponent.
✅ Acceptance criteria
> Remove unused dependency

- package-lock.json
- package.json
- script/mockbigscreenplayer.js
- script/version.js
📺 What
Update mockBigscreenPlayer.
> Tickets: IPLAYERTVV1-10142
🛠 How
Added `getFrameworkVersion` to `mockBigscreenPlayer` to return mocked value of `bigscreenPlayer` version.
> Added getFrameworkVersion() to mockBigscreenPlayer

- .eslintignore
- development/index.js
- package-lock.json
- package.json
- webpack.config.js
📺 What
Currently standalone development has to go through the example app, which is clunky to update on the fly and requires a rebuild each time. This just leverages webpack-dev-server to do the hot reloading for us.
🛠 How
Use webpack-dev-server. Enable quicker rapid prototyping locally without an application integration.
`npm start` will get you a webpack-dev-server with hot module replacement
> Improve the development experience

- package-lock.json
- package.json
- script-test/domhelpers.js
- script/captions.js
- script/domhelpers.js
- script/version.js
📺 What
Add 'urn:ebu:tt:distribution:2018-04' to the standards checked to determine the namespace of a captions document and which id attribute to parse on.
🛠 How
Parse on the same attributes and values as 'urn:ebu:tt:distribution:2014-01'.
♿  Accessibility
Captions should display correctly given a new standard subtitle document.
✅ Acceptance criteria 
* [] [Captions are displayed in the accepted style and timing]
> support parsing urn:ebu:tt:distribution:2018-04 

- package-lock.json
- package.json
- script/captions.js
- script/version.js
📺 What
In some cases, multiple `p` tags can cause subtitles to cover more of the video than is desirable.
🛠 How
Make sure the margin of the paragraph tags that are created is `0px`.
> Improve Caption Spacing

- package-lock.json
- package.json
- script-test/manifest/manifestmodifiertest.js
- script/manifest/manifestmodifier.js
- script/mediasources.js
- script/version.js
📺 What
Stop incorrectly failing over to the next CDN for simulcast audio.
> Ticket: [IPLAYERTVV1-10390](https://jira.dev.bbc.co.uk/browse/IPLAYERTVV1-10390)
🛠 How
Overwrite the serviceLocation property on the manifest with the correct value (an absolute url).
> Modify manifest  service location to absolute url

- package-lock.json
- package.json
- script-test/playbackstrategies/msestrategytest.js
- script/playbackstrategy/msestrategy.js
- script/version.js
📺 What
For most MSE devices, we throw TWO buffering state changes from `bigscreen-player`, one on the media element's `waiting` event, and another on the media element's `seeking` event. The first one will be suppressed when seeking, but the second will not. We need to throw one `WAITING` event to stop reporting false buffering.
[Tickets: IPLAYERTVV1-10185](https://jira.dev.bbc.co.uk/browse/IPLAYERTVV1-10185)
🛠 How
Set seeking state when `setCurrentTime` is called in `msestrategy`. Throw onw `WAITING` for the first seeking/waiting event when we are in the seeking state.
> Multiple seek event bug

- package-lock.json
- package.json
- script-test/playbackstrategies/modifiers/html5tests.js
- script-test/playbackstrategies/msestrategytest.js
- script/playbackstrategy/modifiers/html5.js
- script/playbackstrategy/msestrategy.js
- script/version.js
📺 What
Spotted in automated testing telemetry. Calling tearDown will set `eventCallbacks` to `undefined` causing a type error when a media element emits an event.
Spotted during
> Tickets: IPLAYERTVV1-9375
🛠 How
Guard iterating through the `eventCallbacks` if the array is `undefined`.
> Add a guard to eventCallbacks

- package-lock.json
- package.json
- script/bigscreenplayer.js
- script/version.js
📺 What
Synchronously tearing down the player based upon an event will not log the event that caused the teardown.
🛠 How
Log the event before actioning callbacks registered to the event.
> Log events before actioning callbacks

- package-lock.json
- package.json
- script-test/dynamicwindowutilstest.js
- script-test/playbackstrategies/msestrategytest.js
- script/dynamicwindowutils.js
- script/playbackstrategy/legacyplayeradapter.js
- script/playbackstrategy/msestrategy.js
- script/version.js
📺 What
Seeking to the beginning of the sliding window on a MSE device will resume play from a paused state.
> Tickets: [IPLAYERTVV1-9679](https://jira.dev.bbc.co.uk/browse/IPLAYERTVV1-9679)
🛠 How
When seeking to a point in the video, we check if the new time is at the start of the sliding window. If it is at the start and we are in a paused state then play the asset.
✅ Acceptance criteria [Optional]
[MANDATORY for cross-team reviews]
> Auto Resume Live Asset for MSE Devices 

- README.md
- package-lock.json
- package.json
- script-test/bigscreenplayertest.js
- script/bigscreenplayer.js
- script/version.js
📺 What
This adds `registerForSubtitleChanges()`. The listener is called whenever `setSubtitlesEnabled` is.
> Tickets: IPLAYERTVV1-11166
🛠 How
Implement `registerForSubtitleChanges` and `unregisterForSubtitleChanges` using the other similar functions as an example.
✅ Acceptance criteria
> Add ability to notified to subtitles being turned on/off

- .travis.yml
📺 What
Add travis config to deploy release tags from master.
> Tickets: N/A
🛠 How
Use a publish token from NPM that is securely stored on Travis to deploy an NPM package from a tag on the master branch.
> add travis config to deploy release tags from master

- package-lock.json
- script-test/playbackstrategies/modifiers/live/restartabletest.js
- script-test/playbackstrategies/modifiers/live/seekabletest.js
- script-test/playbackstrategies/msestrategytest.js
- script/playbackstrategy/modifiers/live/restartable.js
- script/playbackstrategy/modifiers/live/seekable.js
- script/playbackstrategy/modifiers/mediaplayerbase.js
- script/playbackstrategy/msestrategy.js
📺 What
This fixes auto resume not triggering for MSE and native seekable whilst paused and seeking to anywhere other than the start.
> Tickets: IPLAYERTVV1-11210
🛠 How
- Starts auto resume timer if paused and seeking
(MSE is triggered after a 'seeked' event)
(Native seekable is on playFrom if postseekstate was paused.)
- Stops STATUS events clearing auto resume timer for native implementations
- Verifies that only SLIDING windows start the timeout
> Auto resume after seek whilst paused

- script-test/readyhelpertest.js
- script/readyhelper.js
📺 What
Protect against a user not passing an onSuccess callback to the init function of BSP.
[Add the jira ticket and/or the ADR to this PR]
> Tickets: IPLAYERTVV1-10894
🛠 How
check the callback is not undefined before calling it.
> Protect against undefined onSuccess callback

- script/subtitles/captionscontainer.js
📺 What
Fixes bug where incorrect arguments were sent to Renderer from CaptionsContainer, resulting in captions being permanently autostarted.
🛠 How
Pass `autoStart` as the correct (4th) argument into Renderer.
> correct the arguments sent to renderer

- package-lock.json
- package.json
- script-test/playercomponenttest.js
- script-test/subtitles/imscsubtitles.js
- script-test/subtitles/subtitles.js
- script/playercomponent.js
- script/subtitles/imscsubtitles.js
- script/subtitles/subtitles.js
📺 What
Allow subtitles customisation options to passed into BSP on initialisation.
> Tickets: [IPLAYERTVV1-11933](https://jira.dev.bbc.co.uk/browse/IPLAYERTVV1-11933)
🛠 How
Add a subtitles customisation object to bigscreenPlayerData.
Take `bbc/imscJS#v1.0.3` which has an API for customising subtitles appearance.
✅ Testing 
> Subtitle Customisation Defaults

- script-test/mediasourcestest.js
- script/mediasources.js
📺 What
Currently, in some instances the first CDN is skipped as our check to determine whether it is the first CDN or not fails due to the `serviceLocation` URL from the manifest not always matching the CDN URLs passed in exactly.
> Tickets: IPLAYERTVV1-12007
🛠 How
Updates the logic for `isFirstManifest` to compare the domain of the serviceLocation instead of the full URL. This method uses a regex to pull out the hostname.
> Update isFirstManifest Logic to only compare Hosts 

- script-test/manifest/manifestmodifiertest.js
- script/manifest/manifestmodifier.js
📺 What
Playback can failover with minimal user impact using the internal dash.js failover mechanism. Normally this would require an array of BaseUrls to be supplied in the Dash MPD, but this works around that mechanism and allows it to be done without.
🛠 How
- Ignore that there isn't a `BaseUrl` in the parsed manifest.
- Assume the content paths are the same across the supplied CDNs (see use of sources in `ManifestUpdater`).
- Refactor the code to be more readable.
✅ Testing 
| Test engineer sign off | ✅ |
> BaseUrl failover for CDNs without a BaseUrl in the manifest (MSE Strategy)

- script-test/subtitles/imscsubtitles.js
- script-test/subtitles/legacysubtitles.js
- script-test/subtitles/subtitles.js
- script/bigscreenplayer.js
- script/subtitles/imscsubtitles.js
- script/subtitles/legacysubtitles.js
- script/subtitles/subtitles.js
- script/utils/timeutils.js
📺 What
Adds ability to display subtitles for LIVE content
> Tickets: IPLAYERTVV1-11997
🛠 How
Moves loading of captions xml into subtitle containers (imsc and legacy). For live playback using imsc.js, individual fragments are downloaded when needed. The correct segment to render is determined and passed to imsc.js.
[MANDATORY for contributions being tested and released by the contributing team]
[How will this change be tested?]
♿  Accessibility [optional]
Adds the ability to display subtitles for live content.
> Live subtitles

- README.md
- development/index.js
- script-test/bigscreenplayertest.js
- script-test/mediasourcestest.js
- script-test/playbackstrategies/msestrategytest.js
- script-test/subtitles/imscsubtitles.js
- script-test/subtitles/legacysubtitles.js
- script-test/subtitles/subtitles.js
- script/bigscreenplayer.js
- script/mediasources.js
- script/subtitles/imscsubtitles.js
- script/subtitles/legacysubtitles.js
- script/subtitles/subtitles.js
- script/utils/playbackutils.js
📺 What
Introduce CDN failover capability for subtitles.
> Tickets: [IPLAYERTVV1-11794](https://jira.dev.bbc.co.uk/browse/IPLAYERTVV1-11794)
🛠 How
- initialise BigscreenPlayer with a captions array.
- failover to subsequent sources if loading the subtitles xml is unsuccessful.
✅ Testing 
✅ Acceptance criteria [Optional]
> Subtitle CDN failover

- README.md
- script-test/bigscreenplayertest.js
- script-test/mediasourcestest.js
- script-test/playbackstrategies/msestrategytest.js
- script-test/subtitles/imscsubtitles.js
- script-test/subtitles/legacysubtitles.js
- script/bigscreenplayer.js
- script/mediasources.js
- script/subtitles/imscsubtitles.js
- script/subtitles/legacysubtitles.js
📺 What
The XHR timeout for sidecar loaded subtitles was set to a static 5000ms in a previous PR. This makes the value configurable per initialisation of the player.
> Tickets: IPLAYERTVV1-11795 
🛠 How
-Add an optional `media.subtitlesRequestTimeout` to the media object used to initialise `bigscreenplayer`.
- Initialise `mediasources` with the media block instead of adding an additional parameter deriving from that object to the init interface.
- Refactor some `mediasources` tests while in the area.
✅ Testing 
> Make the subtitles request timeout configurable

- script-test/mediasourcestest.js
- script-test/subtitles/imscsubtitles.js
- script-test/subtitles/legacysubtitles.js
- script/mediasources.js
- script/subtitles/imscsubtitles.js
- script/subtitles/legacysubtitles.js
📺 What
Report current CDN through subtitle error plugins where appropriate (load, timeout, xml errors)
> Tickets: IPLAYERTVV1-11795
🛠 How
Expose current subtitle cdn on `mediasources`. Move subtitle error plugin into media sources and fire whenever failover is attempted, with a severity level of FAILOVER or FATAL, depending on whether there are further cdns to attempt. 
| Test engineer sign off | ✅ |
[How will this change be tested?]
> Report CDN as an event through subtitle error plugins

- script-test/subtitles/imscsubtitles.js
- script-test/subtitles/subtitles.js
- script/subtitles/imscsubtitles.js
📺 What
Also support `top`, `bottom` and `right` percentage on `SafePosition` for the subtitle preview.
This will give the UI team more flexibility on the position of the menu. I.e. it doesn't need to be fixed to the left of the screen.
Follow up to https://github.com/bbc/bigscreen-player/pull/193
Fixes https://github.com/bbc/bigscreen-player/issues/195
> Tickets: IPLAYERTVV1-12243
🛠 How
- Also handle `top`, `right` and `bottom` (defaulting them to 0 to preserve backwards compatibilty)
- Add some tests that the preview dom element is correct.
Probably good enough to get this version in an app branch and check that the dom element looks correct?
| Test engineer sign off | ✅  |
| ---- | …
> Subtitle Customisation: Also support `top`, `bottom` and `right` percentage on`SafePosition`

- script-test/subtitles/imscsubtitles.js
📺 What
Updates some tests for IMCS subtitles to check the HTML element style properties, instead of the rendered HTML string. 
This stops the problem where browsers may interpret CSS styles and modify them.
In this case, Chrome was changing:
```
<div id="subtitlesPreview" style="position: absolute; top: 1px; right: 1px; bottom: 1px; left: 1px;"></div>
```
to:
```
<div id="subtitlesPreview" style="position: absolute; inset: 1px;"></div>
```
Notice the individual locations were replaced by a single `inset` value.
This only matters when you're not running the Jasmine test runner using the headless Chrome provided by `grunt-contrib-jasmine` package and instead running it in a more up-to-date local browser on your desktop.
🛠 How
Assert against the `subsElement` object and it's `style` …
> Fix IMSC subs tests when running Jasmine in local browser

- script-test/bigscreenplayertest.js
- script-test/playbackstrategies/basicstrategytest.js
- script-test/playbackstrategies/legacyplayeradaptortest.js
- script-test/playbackstrategies/modifiers/html5tests.js
- script-test/playbackstrategies/msestrategytest.js
- script-test/playercomponenttest.js
- script/bigscreenplayer.js
- script/mockbigscreenplayer.js
- script/playbackstrategy/basicstrategy.js
- script/playbackstrategy/legacyplayeradapter.js
- script/playbackstrategy/mockstrategy.js
- script/playbackstrategy/modifiers/html5.js
- script/playbackstrategy/modifiers/samsungmaple.js
- script/playbackstrategy/modifiers/samsungstreaming.js
- script/playbackstrategy/modifiers/samsungstreaming2015.js
- script/playbackstrategy/msestrategy.js
- script/playercomponent.js
📺 What
Add ability to set the playback rate
> Tickets: IPLAYERTVV1-12315
🛠 How
Add api methods for get and set.
When setting:
- MSE strategy - will call method on dash.js
- Native strategy - will set the playback rate directly on the mediaElement (only for the html5 media player - so will **not** currently work for live or other players such as cehtml using native strategy)
- Basic strategy - will set playback rate directly
When getting - for native strategy, attempting to getPlaybackRate on anything other than the standard html5 mediaPlayer will result in a return value of 1.0. This is because you cannot _**set**_ the rate for these non-standard players.
> Ability to set/get playback rate

- script/debugger/debugview.js
📺 What
Remove line space on right hand side of debug tool.
> Tickets: N/A
🛠 How
Remove one of the `\n`'s
👀 See
Original line spacing - some fields can easily be pushed off the bottom - this is exacerbated when using long url:
New spacing:
> Remove line space on right hand side of debug tool

- script-test/utils/callcallbackstest.js
📺 What
The defer exceptions PR recently added this test, which causes other tests to fail occasionally on the CI.
> Tickets: N/A
🛠 How
Mock out time with the jasmine clock, then progress time inside the expectation that catches the error.
> Catch async error thrown outside of test scope

- script-test/utils/deferexceptiontest.js
📺 What
This test occasionally causes other tests to fail because the error is deferred by a setTimeout.
> Tickets: N/A
🛠 How
Similar to #228 this mocks out time to force the error to be thrown and caught by the test.
> Handle async uncaught error in the test suite

- script/debugger/debugview.js
- script/mediasources.js
📺 What
* Strip down URLs on the debug tool.
🛠 How
* Use stripQueryParamAndHash on the displayed URLs
👀 See
Before:
After:
> Debug tool readability improvements

- script-test/playbackstrategies/legacyplayeradaptortest.js
- script/playbackstrategy/legacyplayeradapter.js
📺 What
_I recommend disabling white space changes to review_
'restartable' devices to not have a `playFrom` method, but we were still trying to call it sometimes, causing errors.
We now check if it's there before calling it, the same way we do for other optional methods.
Interestingly there was a test that made sure this was broken 😆 : "restartable HMTL5 Live Player should not have methods for playFrom"
> Tickets: IPLAYERTVV1-12491
🛠 How
Check the function exists before calling it.
- `setCurrentTime` may result in the wrong current time for a bit, but won't throw an error anymore. This is safer than making `setCurrentTime` a no-op, leaving the known wrong current time bug.
- `play()` will flip `isPaused()` to `false`, but will not start playback if the content has ended. This is a safer …
> legacyplayeradapter: do not call `playFrom` if not implemented

- script-test/subtitles/imscsubtitles.js
- script/subtitles/imscsubtitles.js
📺 What
Allows the XML declaration to contain more generic content including the usage of both single and double quotation marks 
> Tickets: IPLAYERTVV1-12583
🛠 How
Update the regex used to match the declaration in the `.split` function when preparing the document for IMSC.
✅ Acceptance criteria
> Make subtitle header XML split more general

- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
- src/plugins.js
📺 What
Allow consumers access to the parsed manifest info and also know about any changes in rendered represenation.
> Tickets: IPLAYERTVV1-12875
🛠 How
Add two plugins `onManifestLoaded` and `onQualityChangedRendered`. 
Manual testing that plugins are correctly emitted.
> Emit manifest and render changed events

- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
📺 What
Given the live delay for MSE strategy means you shouldn't be playing closer than that value to the end of the stream, update the seekable range end, so that clients aren't informed that they can seek further forward than they can.
> Tickets: IPLAYERTVV1-13509
🛠 How
For dynamic streams, using the MSE strategy, subtract the value of `liveDelay` from the DVR Info end before returning.
✅ Testing
| Test engineer sign off | ✅ |
> Seekable range end takes live delay into account

- src/utils/loadurl.js
📺 What
Allow XHR requests for the manifest and subtitles to return a HTTP status of 0.
As per the [XHR MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readystatechange_event), it shows that a status code of 0 can be acceptable as a success response. 
This PR allows that scenario in case we have been rejecting responses that actually have valid data. 
🛠 How
Update the `loadUrl` script to allow status code of 0 to be classes as successful and continue with the request parsing.
> Allow HTTP status code 0 as successful response when loading manifest and subtitles files

- src/utils/loadurl.js
📺 What
In #271 we allowed a status code of `0` to be treated as a success response in `loadUrl` which is used when fetching manifests and subtitle files. 
🛠 How
Update `loadUrl.js` to not explicitly allow status code `0` as a successful response.
> Treat XHR status code 0 as error in loadUrl

- package.json
- src/bigscreenplayer.js
- src/bigscreenplayer.test.js
- src/manifest/manifestparser.js
- src/manifest/manifestparser.test.js
- src/mediasources.js
- src/mediasources.test.js
- src/playercomponent.js
- src/pluginenums.js
- src/plugins.js
📺 What
Currently there is no way to know manifest parsing has failed. This PR provides a plugin hook `onManifestParseError` and explicitly defines the fallback behaviour of ManifestParser.
> Tickets: N/A
🛠 How
- Add `onManifestParseError` to the plugin interface.
- Change returning undefined from `convertEpochMsToVideoTimeSeconds` and `convertVideoTimeSecondsToEpochMs` to return null.
> Handle and report manifest errors and provide a fallback

- package-lock.json
- package.json
📺 What
Update dash.js dependency (contains fixes for ending live event streams).
> Tickets: IPLAYERTVV1-13093
🛠 How
Update package and package-lock files.
> Update dash.js dependency

- .github/workflows/npm-publish.yml
📺 What
Fix the NPM Publish Github Action by removing the linting step.
Linting occurs on PR checks and pre-commit so doesn't need to also run on publish.
🛠 How
Remove linting step from publish Github Action
> Remove linting step from publish Github Action

- src/subtitles/imscsubtitles.js
📺 What
Currently seeking back in time during playback does not clean up subtitles, so the subtitles displayed before seeking are still visible. This ticket fixes this bug.
> Tickets: IPLAYERTVV1-12266
🛠 How
Cleans up current subtitles element if current time is behind the display time of the subtitle currently on sceen.
> Fix subtitles not cleaned up when seeking back

- package.json
📺 What
Fix issue where installing this package as a dependency in a project causes errors due to husky install step recently introduced. 
🛠 How
Add check to only install husky if `.git` directory is there. When installed as a dependency, this won't be there. 
Also removed some files from the `files` array in the `package.json` as they are included by default.
> Fix installation issues caused by Husky

- src/playbackstrategy/msestrategy.js
📺 What
Removes fragment info from playerInfoUpdate plugin
🛠 How
Removes the code from MSE strategy on metric updated.
> Removed fragment info from playerInfoUpdate plugin

- docs/tutorials/00-getting-started.md
- docs/tutorials/live-streaming.md
- docs/tutorials/playback-strategies.md
- docs/tutorials/tutorials.json
- index.html
- package-lock.json
- package.json
- src/bigscreenplayer.js
- src/debugger/chronicle.js
- src/debugger/chronicle.test.js
- src/debugger/debugpresenter.js
- src/debugger/debugpresenter.test.js
- src/debugger/debugtool.js
- src/debugger/debugtool.test.js
- src/manifest/manifestloader.js
- src/manifest/manifestloader.test.js
- src/manifest/manifestparser.js
- src/manifest/manifestparser.test.js
- src/manifest/stubData/dashmanifests.js
- src/mediasources.js
- src/mediasources.test.js
- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
- src/testutils/geterror.js
- src/typedefs.js
📺 What
Get wall-clock time from the `<UTCTiming>` element present in dynamic DASH manifests.
> Ticket: [BADGERS-177](https://jira.dev.bbc.co.uk/browse/BADGERS-177)
If `serverDate` is passed into bigscreen-player on `init` that timing will be used to derive times from the _first_ manifest only. If a new manifest is fetched, or the current manifest is refreshed, then wall-clock time will be derived from `<UTCTiming>`.
Note:
- This is a PR to merge into branch `badgers-177`, not `master`. I've chunked the ticket into two PRs to make reviews easier.
- Therefore, this ticket does not fix:
+ `timeCorrectionSeconds` not being updated on failover/refresh (closure bug).
+ MPD time being passed as availability time on a simulcast failover by using the POSIX time anchor, causing restart point to be …
> BADGERS-177 Use `UTCTiming` for wall-clock time

- src/bigscreenplayer.js
- src/bigscreenplayer.test.js
- src/manifest/stubData/dashmanifests.js
- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
- src/playercomponent.js
- src/utils/mse/build-source-anchor.js
- src/utils/mse/build-source-anchor.test.js
📺 What
Pass current MPD time to Dash.js to restart playback with a new source at the same point in time on CDN failover.
🛠 How
- Move `buildSourceAnchor` to a new file. Make it handle MPD time and video time.
- Modify MSEStrategy to pass failover time as an MPD time instead of a video time.
Note:
This is a PR to merge into branch badgers-177, not master. I've chunked the ticket into two PRs to make reviews easier.
> BADGERS-177 Failover with MPD times in MSE strategy

- src/testutils/geterror.js
📺 What
Update a jsdoc comment that breaks the `docs` build step.
🛠 How
- Specify `Function` as the param type
> fix: change the geterror jsdoc param to Function

- src/bigscreenplayer.js
- src/typedefs.js
📺 What
This documents some bigscreen-player API functions. 
🛠 How
- Add JSDoc comments and in some cases typedefs for undocumented functions.
> Add missing API docs

- package-lock.json
- package.json
📺 What
Title.
🛠 How
Take new Dash.js release.
> upstream fix: remove prepack from Dash.js

- package-lock.json
- package.json
📺 What
Take bbc/dash.js#smp-v4.7.1-2 which guards synthetic media events based on ready state. 
🛠 How
- Update the alias tag
> Update dash.js to smp-v4.7.1-2

- eslint.config.js
- src/bigscreenplayer.js
- src/playbackstrategy/legacyplayeradapter.js
- src/playbackstrategy/msestrategy.js
📺 What
The `initial-playback-time` can be logged to the `DebugTool` as a dynamic metric. This was only done for Native playback (in `legacyPlayerAdapter.js`). This gives visibility to the initial time for MSE devices too.
🛠 How
Adds the DebugTool call in `msestrategy.js` (only for initial load, not on cdn failover).
> Include initial-playback-time and playback-strategy in DebugTool for all sessions

- rollup.dev.config.js
📺 What
Update the live reload watcher.
🛠 How
Update the live-reload rollup plugin usage to watch `dist-local` and `index.html`.
> Live reload on changes to the development build

- src/subtitles/imscsubtitles.js
📺 What
Due to a performance issue running string.split on large subtitle segments, replace the use of string.split with a more efficient replacement.
🛠 How
Replace string.split with alternative use of string.replace.
> Do not use string.split on non-segmented subtitles

- package-lock.json
- package.json
📺 What
Make use of the latest (`v4.7.3-2`) release of bbc/dash.js.
This allows devices to be configured to bypass the check for the `loadedmetadata` (see https://github.com/bbc/dash.js/pull/92)
🛠 How
Update package.json and package-lock.json
> Update dash.js dependency (to include use seek without ready state check)

- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
📺 What
Prevents the 3 BSP Specific Settings, [`failoverResetTime`](https://bbc.github.io/bigscreen-player/api/tutorial-02-settings-and-overrides.html#failoverresettime), [`failoversort`](https://bbc.github.io/bigscreen-player/api/tutorial-02-settings-and-overrides.html#failoversort), and [`streaming.seekdurationpadding`](https://bbc.github.io/bigscreen-player/api/tutorial-02-settings-and-overrides.html#streaming.seekdurationpadding) from being passed to DashJS. This prevents spurious warnings from being printed on the console on Dash Initialization.
🛠 How
> Don't pass BSP specific settings to Dash

- src/plugins.js
- src/plugins.test.js
📺 What
fix: handle calling plugins with context
🛠 How
- Use the whole object as `this` context when mapping selected plugins.
> Handle calling plugins with context

- src/subtitles/legacysubtitles.js
📺 What
Adds legacy subtitle styling for 1080 layout devices as well as defaulting to 720.
🛠 How
Checks the `parentElement`'s `clientHeight`. Change the styling values depending on result.
> Ensure legacy subtitle styling is applied for both 720 and 1080 height video containers

- package-lock.json
- package.json
- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
📺 What
Manually refresh the manifest on a manifest validity changed event. This is only implemented for dynamic event streams that can end (Growing window type).
🛠 How
- Call `mediaPlayer.refreshManifest(callback)`
- Use updated dash.js fork release that has configurable internal ended behaviour.
> refresh manifest on validity changed event

- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
📺 What
Publish errors when segment downloads fail, and there is only one available CDN remaining (none left to failover to). 
This prevents the player from entering an infinite buffering state where segments aren't being requested and the CDN isn't failing over, instead forcing the player to fatal error.
🛠 How
Only ignores `DOWNLOAD_CONTENT` & `DOWNLOAD_INIT_SEGMENT` errors when there is more than one available CDN remaining; otherwise we publish the error.
> BADGERS-535: publish error when segment download fails on final CDN

- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
📺 What
Don't apply `liveDelay` to `WindowTypes.STATIC`, supersedes #301 
🛠 How
Add a checks for `windowType` in `getClampedTime()` and use the implementation from `getClampedTimeForLive()` for `WindowTypes.SLIDING`, the original implementation for `WindowTypes.GROWING`, and #301, with `seekDurationPadding`, for `WindowTypes.STATIC`. Refactored into a single expression with ternary checks preceeding. 
👀 See
#301
> Don't apply `liveDelay` to `WindowTypes.STATIC`

- docs/tutorials/Subtitles.md
📺 What
Fix broken anchor link in subtitles tutorial.
🛠 How
Include the (encoded) '?' character in the anchor link.
> Fix broken anchor link in subtitles tutorial

- src/playbackstrategy/msestrategy.js
📺 What
Augment the `onManifestLoaded` plugin with the loading time for MSE strategy devices.
🛠 How
Use dash.js' `manifestLoadingFinished` event to obtain the time taken to load the manifest. Store and send this data when calling the  `onManifestLoaded` plugin
> Augment onManifestLoaded plugin with the manifest load time

- docs/tutorials/Plugins.md
- index.html
- src/playbackstrategy/msestrategy.js
- src/plugins.js
📺 What
Expose the DashJS `onQualityChangeRequested` Event via the Plugin System, also includes average Throughput
🛠 How
```js
mediaPlayer.on(DashJSEvents.QUALITY_CHANGE_REQUESTED, ...)
```
> Plugin for `onQualityChangeRequested`

- index.html
- src/bigscreenplayer.js
- src/bigscreenplayer.test.js
- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
- src/playercomponent.js
📺 What
Makes BroadcastMixAD available for MSE devices.
🛠 How
* Adds a set of new APIs that check for the availability, whether its enabled and ability to turn it on or off.
* Adds the ability to turn BroadcastMixAD on by default (if the track exists).
* Availability is determined from the audio properties in the manifest. Accessibility schema and the alternate role.
* Use dash.js to change the tracks between BroadcastMixAD and main audio.
* Adds unit tests.
> MSE BroadcastMixAD Support

- .husky/pre-push
📺 What
Runs `git stash push -qu` before the prepush hook tests and runs `git stash pop -q` after them. This allows for unstaged in development tests to be present without having to pass whilst still verifying what is being pushed. Prevents potentially running `--no-verify` or similar to just get something pushed.
🛠 How
Source Control
✅ Testing
Tested by changing a test to fail (`expect(true).toBe(false)`) and not staging it whilst pushing this change - test was not included in index and did not affect prepush hook checks.
> Stash before running prepush hook tests

- src/mockbigscreenplayer.js
📺 What
"Fix" (read: hack) the BigscreenPlayer mock so it doesn't throw `TypeError` etc. The time API is not fixed so the mock is still broken. This carries us through until we can decomission all downstream tests that use the mock.
🛠 How
Add new functions. Keep around old functions as "compatibility functions"
> BADGERS-245: Hack the BigscreenPlayer mock

- src/subtitles/imscsubtitles.js
- src/subtitles/imscsubtitles.test.js
📺 What
Fixes a race condition between imscstrategy and the player.
🛠 How
Don't accept zero as an valid time. Drawback is subtitles load later (after the stream instead of in parallel). A more robust solution could compare the calculated segment number with the segment start number in the manifest.
> fix(imsc): subtitle startup race condition

- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
📺 What
Fixes an issue where `cached.currentTime` was not being set if `mediaElement.currentTime` was `0`. In situations where the `load` was called with no `initialPlaybackTime` and the `mediaElement.currentTime` was not naturally updated, the time would stay as `undefined`, causing the `readyHelper` to not call the success callback and causing BSP to be stuck in an unready state.
🛠 How
Add, correct and unify guards around the setting of `cached.currentTime` in MSE strategy to ensure the value is a number.
✅ Testing
Added a unit test covering the aforementioned scenario.
>  Add Guards Around Setting `cached.currentTime`

- src/mockbigscreenplayer.js
📺 What
Corrects a function name used in `MockBigScreenPlayer`.
🛠 How
Renames `setAudioDescribedEnabled` to `setAudioDescribed` to match the actual API.
> Use the Correct Name for Functions in MockBigScreenPlayer

- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
📺 What
Dash.js caches the last track used in local storage and selects the audio track based on selection priority and then max bitrate. This can result in the BroadcastMixAD (Audio Described) being selected against the users preference. This can manifest in two scenarios.
1. When the last track selected was BroadcastMixAD, the user turns off their preference out of stream and then the user plays a stream with a BroadcastMixAD track, the BroadcastMixAD track will be selected.
2. If the BroadcastMixAD track has a higher track selection priority in the manifest or has a higher max bitrate, the BroadcastMixAD audio track will be selected.
In both scenarios, the BroadcastMixAD track is selected when the users AD preference is off. This PR disables dash.js's media track caching and sets an …
> Add Correct Initial Audio Settings

- .releasinator.json
📺 What
In preparation for a change to the release automation, adds a config file for the bot "releasinator" (previously tvr-buildatron)
🛠 How
Copy existing release behaviour over into a config file in the root directory.
✅ Testing 
After this change is merged, and the change to the release automation happens (likely Fri 28th March) a secondary "test" PR will be opened and merged. 
If the changes are successful a "test" release will be created and should not have any particular differences other than the name/image of the bot making the release.
> Add releasinator config file

- src/debugger/chronicle.test.ts
- src/debugger/chronicle.ts
- src/debugger/debugtool.test.ts
- src/debugger/debugtool.ts
- src/debugger/debugview.ts
- src/debugger/debugviewcontroller.test.ts
- src/debugger/debugviewcontroller.ts
- src/models/mediakinds.ts
- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
📺 What
Title. The on-screen fields are derived from Chronicle records:
- `video-download-quality`
- `video-playback-quality`
- `video-max-quality`
- `audio-download-quality`
- `audio-playback-quality`
- `audio-max-quality`
Also removes the message on quality switch rendered, and reformats the message on quality switch requested. 
🛠 How
Replaces the fields `bitrate`, `representation-audio`, and `representation-video`. Merges `playback-rate` into the `media-element-state` field in the on-screen debugger to save some vertical space.
✅ Testing
| ---------------------- | --- |
👀 See
> Add audio-quality, video-quality, and max-bitrate to the on-screen debugger

- package-lock.json
- package.json
📺 What
Updates version of Dash.js
🛠 How
Updates the version of Dash.js to `smp-v4.7.3-6` which adds a new catchup mechanism for low latency that switches playback rates in steps instead of on a continuum. This catchup mechanism is expected to be better supported by TVs.
Additionally, introduces a `liveThreshold` to indicate when the user is too far away from the bleeding edge to be considered live.
Fixes issues preventing `maxDrift` from being disabled
Finally, ensures synthetic stalls behave as expected when using catchup in low-latency mode
> Add new Low Latency Catchup Algorithm

- src/mediasources.ts
- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
- src/types.ts
📺 What
Take the full dash.js entrypoint vs `index_mediaplayerOnly`, pass through dash.js protection data.
🛠 How
- Update the dash.js entrypoint. Use the index vs the built `main` package entrypoint to allow consuming applications to decide what to bundle.
- Use the same shape protection data as dash.js within the optional `media.protectionData`. This is exposed via the types.
- Expose the protection data within mediaSources with the `currentProtectionData` function.
- Set protection data on the dash.js media player.
> Use full entrypoint of dash.js, allow protection data to be used

- src/playbackstrategy/msestrategy.js
- src/playbackstrategy/msestrategy.test.js
📺 What
* Ensure AD persists on source change
🛠 How
* Move setting track preference down into modify source from initial load.
* On track change update audiodescribed.enable to reflect current state.
> Ensure AD persists on source change

- package-lock.json
- package.json
📺 What
Updates Dash.js with a new version that includes a bug fix for buffer level reporting when using DVB metrics.
🛠 How
Fixes an issue in Dash.js where the buffer level of text tacks is continually reported even when the track is disabled.
The buffer level value reported is a minimum. This results in the DVB Buffer Level being reported as 0 when subtitles are not in use.
> Update Dash.js Version with Buffer Level Fix

- src/playercomponent.js
- src/playercomponent.test.js
📺 What
Ensure the order of the playback strategy by not passing the abort signal further down (without updating the strategies signature).
🛠 How
Removes `abortSignal` parameter in the call to `strategy`.
> Don't Pass Abort Signal Into Playback Strategy

- package-lock.json
- package.json
📺 What
Updates Dash.js to smp-v4.7.3-13
🛠 How
Updates Dash.js to smp-v4.7.3-13, brings in change to ignore WebKit devices from the `videoFramesNotAdvancing` method.
> Video frames not advancing ignore webkit

- src/bigscreenplayer.js
- src/bigscreenplayer.test.js
- src/subtitles/embeddedsubtitles.js
- src/subtitles/embeddedsubtitles.test.js
- src/subtitles/imscsubtitles.js
- src/subtitles/imscsubtitles.test.js
- src/subtitles/legacysubtitles.js
- src/subtitles/legacysubtitles.test.js
- src/subtitles/renderer.js
- src/subtitles/subtitles.js
- src/subtitles/subtitles.test.js
- src/types.ts
📺 What
Add Subtitles Always on Top option for Legacy and IMSC Subs, Embedded Subs does not support this option currently
🛠 How
- Add Always on Top option to subtitle API - sets Z value to INT32_MAX (2147483647)
- Refactor Subtitle API
> Add Subtitles Always on Top option

- docs/tutorials/00-getting-started.md
- src/bigscreenplayer.js
- src/playbackstrategy/msestrategy.js
- src/playercomponent.js
- src/playercomponent.test.js
- src/types.ts
📺 What
For MSE browsers, show the headers in `debug.fragmentResponseHeaders ` as static fields in the debug tool overlay.
🛠 How
- Add new optional `debug` object to the initialisation data.
- For each header in `fragmentResponseHeaders` display the value from the latest video fragment response.
> Add video fragment response headers to the debug view
